# Generated by Django 4.2 on 2023-05-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Questionnaire", "0002_alter_question_options_remove_question_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Questionnaire.question"
            ),
        ),
    ]
